# Generated by Django 4.2.1 on 2023-10-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_categories_alter_blogpost_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='Subcategories',
        ),
    ]
